/*
 * This file is generated by jOOQ.
 */
package ch.rasc.travellog.db;


import ch.rasc.travellog.db.tables.AppSession;
import ch.rasc.travellog.db.tables.AppUser;
import ch.rasc.travellog.db.tables.Log;
import ch.rasc.travellog.db.tables.LogPhoto;
import ch.rasc.travellog.db.tables.Travel;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code></code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index APP_SESSION_APP_USER_ID = Indexes0.APP_SESSION_APP_USER_ID;
    public static final Index APP_SESSION_PRIMARY = Indexes0.APP_SESSION_PRIMARY;
    public static final Index APP_USER_EMAIL = Indexes0.APP_USER_EMAIL;
    public static final Index APP_USER_PRIMARY = Indexes0.APP_USER_PRIMARY;
    public static final Index LOG_PRIMARY = Indexes0.LOG_PRIMARY;
    public static final Index LOG_TRAVEL_ID = Indexes0.LOG_TRAVEL_ID;
    public static final Index LOG_PHOTO_LOG_ID = Indexes0.LOG_PHOTO_LOG_ID;
    public static final Index LOG_PHOTO_PRIMARY = Indexes0.LOG_PHOTO_PRIMARY;
    public static final Index TRAVEL_APP_USER_ID = Indexes0.TRAVEL_APP_USER_ID;
    public static final Index TRAVEL_PRIMARY = Indexes0.TRAVEL_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index APP_SESSION_APP_USER_ID = Internal.createIndex("app_user_id", AppSession.APP_SESSION, new OrderField[] { AppSession.APP_SESSION.APP_USER_ID }, false);
        public static Index APP_SESSION_PRIMARY = Internal.createIndex("PRIMARY", AppSession.APP_SESSION, new OrderField[] { AppSession.APP_SESSION.ID }, true);
        public static Index APP_USER_EMAIL = Internal.createIndex("email", AppUser.APP_USER, new OrderField[] { AppUser.APP_USER.EMAIL }, true);
        public static Index APP_USER_PRIMARY = Internal.createIndex("PRIMARY", AppUser.APP_USER, new OrderField[] { AppUser.APP_USER.ID }, true);
        public static Index LOG_PRIMARY = Internal.createIndex("PRIMARY", Log.LOG, new OrderField[] { Log.LOG.ID }, true);
        public static Index LOG_TRAVEL_ID = Internal.createIndex("travel_id", Log.LOG, new OrderField[] { Log.LOG.TRAVEL_ID }, false);
        public static Index LOG_PHOTO_LOG_ID = Internal.createIndex("log_id", LogPhoto.LOG_PHOTO, new OrderField[] { LogPhoto.LOG_PHOTO.LOG_ID }, false);
        public static Index LOG_PHOTO_PRIMARY = Internal.createIndex("PRIMARY", LogPhoto.LOG_PHOTO, new OrderField[] { LogPhoto.LOG_PHOTO.ID }, true);
        public static Index TRAVEL_APP_USER_ID = Internal.createIndex("app_user_id", Travel.TRAVEL, new OrderField[] { Travel.TRAVEL.APP_USER_ID }, false);
        public static Index TRAVEL_PRIMARY = Internal.createIndex("PRIMARY", Travel.TRAVEL, new OrderField[] { Travel.TRAVEL.ID }, true);
    }
}
